# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useryoga',
            name='auth_by_sn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useryoga',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useryoga',
            name='extra_data',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
