# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20170307_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_opened',
            field=models.BooleanField(default=True),
        ),
    ]
