# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_project_is_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
