# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20170310_1451'),
        ('app', '0007_contactusmodel_is_new'),
    ]

    operations = [
    ]
