# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20170314_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='nameUA',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='textUA',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfoliocontent',
            name='descriptionUA',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfoliocontent',
            name='nameUA',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
